# CodeRabbit Configuration
# https://docs.coderabbit.ai/configuration
#
# CodeRabbit provides automatic AI-powered code reviews on every PR.
# Pro tier is FREE for open source repositories.

language: en

reviews:
  # Enable automatic reviews on new PRs
  auto_review:
    enabled: true
    drafts: false
    base_branches:
      - main
      - develop

  # Path-specific instructions for reviewers
  path_instructions:
    - path: "**/*.md"
      instructions: |
        Check for:
        - Conventional commits references
        - Protocol compliance (no TODO.md, PROGRESS.md, etc.)
        - Proper YAML frontmatter in agent-docs/

    - path: "scripts/**"
      instructions: |
        Verify:
        - Cross-platform compatibility (bash + PowerShell equivalents)
        - Proper error handling
        - Atomic operation principles

    - path: ".github/workflows/**"
      instructions: |
        Check for:
        - Proper permissions
        - Security best practices
        - Reusable workflow patterns

    - path: "**/*.sh"
      instructions: |
        Verify:
        - POSIX compatibility where possible
        - Proper quoting and escaping
        - Error handling with set -e

    - path: "**/*.ps1"
      instructions: |
        Check for:
        - PowerShell best practices
        - Proper error handling
        - Cross-platform paths

# Chat settings for interactive code discussions
chat:
  auto_reply: true

# Review tone and focus
tone_instructions: |
  Focus on:
  - Atomic commit principles
  - Conventional commits compliance
  - Code maintainability
  - Security considerations
  - Living Context accuracy (for docs/agent-docs/ PRs)
  
  Be constructive and provide actionable suggestions.
  
  For Living Context PRs (branch: living-context/*):
  - Verify dependency version accuracy
  - Check for known CVEs in listed versions
  - Validate intelligent patterns are actionable
  - Ensure quarantine dates follow 14-day rule

# Knowledge base for context
knowledge_base:
  learnings:
    scope: auto
  issues:
    scope: auto
  jira:
    project_keys: []
  linear:
    team_keys: []

# Label configuration for Living Context
labels:
  - name: "living-context"
    description: "Living Context Protocol updates"
  - name: "ai-review-requested"
    description: "AI agents should review this PR"
  - name: "dependency-intelligence"
    description: "Contains dependency analysis"
